### ISSUE TITLE
An Execption/Error

### ISSUE THREAD

**Issue by angelov-1080** [O2theC/CrabChampionSaveManager#10]
Type : <class 'json.decoder.JSONDecodeError'>                                                                           Value : Expecting value: line 1 column 54 (char 53)                                                                     Traceback :                                                                                                               File "CrabChampionSaveManager.py", line 6034, in <module>                                                               File "CrabChampionSaveManager.py", line 2818, in manageBackups                                                          File "CrabChampionSaveManager.py", line 2891, in manageBackupEdit                                                       File "CrabChampionSaveManager.py", line 2951, in editBackupUI                                                           File "CrabChampionSaveManager.py", line 4937, in convertPresetToGameSave                                                File "json\__init__.py", line 346, in loads                                                                             File "json\decoder.py", line 337, in decode                                                                             File "json\decoder.py", line 355, in raw_decode  

This issue appears when Editing a save created from a preset, regardless if you try to apply a weapon mod, perk etc or simply finish editing without altering any of the details of the save

**Comment by O2theC** [comment]
sorry to say but the update broke a lot with the program and along with trying to remake it but with a GUI and not having much free time, well, i haven't got a version for the new update yet, so the program will prob freak out a bit with the new save structure, sorry.
